/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProducaoRouteImport } from './routes/_authenticated/producao'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminRelatoriosConsertosRouteImport } from './routes/_authenticated/admin/relatorios-consertos'
import { Route as AuthenticatedAdminHistoricoRouteImport } from './routes/_authenticated/admin/historico'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProducaoRoute = AuthenticatedProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRelatoriosConsertosRoute =
  AuthenticatedAdminRelatoriosConsertosRouteImport.update({
    id: '/admin/relatorios-consertos',
    path: '/admin/relatorios-consertos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminHistoricoRoute =
  AuthenticatedAdminHistoricoRouteImport.update({
    id: '/admin/historico',
    path: '/admin/historico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/admin/historico': typeof AuthenticatedAdminHistoricoRoute
  '/admin/relatorios-consertos': typeof AuthenticatedAdminRelatoriosConsertosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/historico': typeof AuthenticatedAdminHistoricoRoute
  '/admin/relatorios-consertos': typeof AuthenticatedAdminRelatoriosConsertosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/producao': typeof AuthenticatedProducaoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/historico': typeof AuthenticatedAdminHistoricoRoute
  '/_authenticated/admin/relatorios-consertos': typeof AuthenticatedAdminRelatoriosConsertosRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/producao'
    | '/admin/historico'
    | '/admin/relatorios-consertos'
    | '/admin/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/producao'
    | '/'
    | '/admin/historico'
    | '/admin/relatorios-consertos'
    | '/admin/usuarios'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/producao'
    | '/_authenticated/'
    | '/_authenticated/admin/historico'
    | '/_authenticated/admin/relatorios-consertos'
    | '/_authenticated/admin/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao': {
      id: '/_authenticated/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AuthenticatedProducaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/relatorios-consertos': {
      id: '/_authenticated/admin/relatorios-consertos'
      path: '/admin/relatorios-consertos'
      fullPath: '/admin/relatorios-consertos'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosConsertosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/historico': {
      id: '/_authenticated/admin/historico'
      path: '/admin/historico'
      fullPath: '/admin/historico'
      preLoaderRoute: typeof AuthenticatedAdminHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProducaoRoute: typeof AuthenticatedProducaoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminHistoricoRoute: typeof AuthenticatedAdminHistoricoRoute
  AuthenticatedAdminRelatoriosConsertosRoute: typeof AuthenticatedAdminRelatoriosConsertosRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProducaoRoute: AuthenticatedProducaoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminHistoricoRoute: AuthenticatedAdminHistoricoRoute,
  AuthenticatedAdminRelatoriosConsertosRoute:
    AuthenticatedAdminRelatoriosConsertosRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
